import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const taskContentArea = await readFile(new URL('./TaskContentArea.vue', import.meta.url), 'utf8')
const taskViewModel = await readFile(new URL('../composables/useTaskViewModel.ts', import.meta.url), 'utf8')
const knowledgeTreeNode = await readFile(new URL('./KnowledgeLibrary/KnowledgeTreeNode.vue', import.meta.url), 'utf8')
const knowledgeLibraryTree = await readFile(new URL('./KnowledgeLibrary/KnowledgeLibraryTree.vue', import.meta.url), 'utf8')
const contentSubscriptions = await readFile(new URL('./ContentSubscriptions.vue', import.meta.url), 'utf8')
const useSubscriptions = await readFile(new URL('../composables/useSubscriptions.ts', import.meta.url), 'utf8')

assert.match(taskContentArea, /\['wechat_article', 'homeway_daily_digest', 'homeway_post'\]/)
assert.match(taskContentArea, /marked\.parse\(props\.task\.transcript\)/)
assert.match(taskContentArea, /v-html="compiledTranscriptMarkdown"/)
assert.match(taskViewModel, /\['homeway_daily_digest', 'homeway_post'\]/)
assert.match(taskViewModel, /activeTab\.value = 'transcript'/)
assert.match(knowledgeTreeNode, /source_type === 'homeway_post'/)
assert.match(knowledgeTreeNode, /replace\(\/\^\\d\{4\}-\\d\{2\}-\\d\{2\}\\s\+\//)
assert.match(knowledgeTreeNode, /const expanded = ref\(false\)/)
assert.match(knowledgeTreeNode, /searchActive/)
assert.match(knowledgeLibraryTree, /最新帖子/)
assert.match(contentSubscriptions, /补采一段历史/)
assert.match(contentSubscriptions, /关闭程序后，下次启动会从上次位置继续/)
assert.match(contentSubscriptions, /已扫描到来源边界/)
assert.match(contentSubscriptions, /内容来源/)
assert.match(contentSubscriptions, /小鹅通批量采集/)
assert.match(contentSubscriptions, /openCollectionCapture/)
assert.match(useSubscriptions, /\/backfills/)
